### ISSUE TITLE
HTTPSを強制する

### ISSUE THREAD

**Issue by shokai** [stkay/Gyaon#14]
HTTPSじゃないとweb speech api使えないので、HTTPで来たらHTTPSに飛ばす必要がある

expressだとforece-ssl middlewareを使うと楽
https://www.npmjs.com/package/force-ssl

もちろん自分で書いてもいい

`process.env.NODE_ENV === 'production'` の時のみforce-sslするようにしないとローカルでもhttps://localhostになって開発できなくなるので注意

**Comment by stkay** [comment]
age

**Comment by stkay** [comment]
https://qiita.com/enu-kuro/items/d6fd26abf93fc8dd56b4
