### ISSUE TITLE
音のURLが欲しい

### ISSUE THREAD

**Issue by shokai** [stkay/Gyaon#17]

**Comment by stkay** [comment]
- [ ] liをクリックするとクリップボードにコピーする 392373d92800838d2bab9506e8734df880fbc786
- [ ] 録音完了時にクリップボードにコピーする

**Comment by stkay** [comment]
clipboard.jsを使っているが、クリックイベント(エミュレート不可)しか対応していないので、アップロードと同時にクリップボードに入れるのは難しいっぽい

**Comment by stkay** [comment]
コピー時にフィードバックする 392373d
