### ISSUE TITLE
アップロードが中止されるとサーバが落ちる

### ISSUE THREAD

**Issue by stkay** [stkay/Gyaon#30]
発生条件
- Web版で録音終了直後にブラウザを閉じたとき
- Android版で録音終了直後に新しく音声を録音開始したとき

**Comment by stkay** [comment]
解決方法が <img src="https://emoji.slack-edge.com/T02AFRBD9/wakaland/b5530bb5fd17ed8b.png" width="22px">

**Comment by keroxp** [comment]
取り敢えずスタックトレースを貼りましょう。多分ソケットの接続が切れてヌルポになるとかそういうバグだと思うけど。可能ならtry catchで対応できるかもしれない。

**Comment by shokai** [comment]
![](https://i.gyazo.com/2c7eb51aa90e754527c627d565a40ba0.png)

**Comment by shokai** [comment]
formidableはtry-catchじゃなくてabortedかerrorにイベントかけるのかな
https://www.npmjs.com/package/formidable#aborted
