### ISSUE TITLE
MacのSafari + Gyazzでブラウザが死ぬ

### ISSUE THREAD

**Issue by shokai** [stkay/Gyaon#44]
## 結論

リダイレクトではなくpipeでやってるからじゃないか？と思う

## 現象

https://gyazz-clone.herokuapp.com/masuilab/何か書くと早川が録音して返す

をMacのSafariで開いただけでブラウザが死にます。

Audioの読み込みタイミングを現在のページ開いた瞬間ではなくマウスオーバーにしてみたら、マウスオーバーで死にました。

増井先生のサーバーにある ` [お前のような奴は犯罪者予備軍だと言いましたよね? http://masui.org/387c3d1a91e82ffcf378278b84290f4c.mp3]` だけはMacのSafariで開いても大丈夫なのと、
http://masui.sfc.keio.ac.jp/satake/GyazzSound/ はMacのSafariでも動くので、

つまりgyaonサーバーにある（拡張子リダイレクトされた）音声ファイルをAudioタグで読み込むとSafariで死ぬという事ではないかと思う

**Comment by shokai** [comment]
というかリダイレクトにしない理由がよくわからん
サイズが軽いとはいえpipeはCPU食うし

**Comment by stkay** [comment]
じゃあリダイレクトにします

**Comment by shokai** [comment]
ちなみにexpressだとリダイレクトは `res.redirect('https://~~')` だけなので簡単です

**Comment by stkay** [comment]
fix #44 05ba2f7a524ff981940604753f5a3f06723713c1

**Comment by shokai** [comment]
なおった！ので閉じます
