### ISSUE TITLE
heroku上で.envが無いと怒られるので握りつぶす

### ISSUE THREAD

**Issue by stkay** [stkay/Gyaon#94]

**Comment by shokai** [comment]
それsilentオプション不要になったのでdotenvを最新版に上げれば消えます
https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md#removed-1

**Comment by stkay** [comment]
<img src="https://gyazo.com/b897852e1fdf72ba3a4f13b87ddcd626.png">
